- hosts: Kubernetes_Master
  become: yes
  tasks:
  - name: Start the Cluster
    shell: kubeadm init --prod-network-cidr=10.244.0.0/16 >> cluster.txt
    args: 
      chdir: $HOME
      creates: cluster.txt
  - name: Create .kube Directory
    become: yes
    become_user: ubuntu
    file: 
      path: $HOME/.kube
      state: directory
      mode: 0755
  - name: Copy admin.conf to user's kuve config
    copy: 
      src: /etc/kubernetes/admin.conf
      dest: /home/ubuntu/.kube/config
      remote_src: yes
      owner: ubuntu
  - name: Install pod network
    become: yes
    become_user: ubuntu
    shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/k8s-manifests/kube-flannel-legacy.yml > pod_setup.txt
    args:
      chdir: $HOME
      remote_src: yes
      creates: pod_setup.txt
